### ISSUE TITLE
Please take this down.

### ISSUE THREAD

**Issue by cozyGalvinism** [Mae-TM/TGPublic#1]
Heya!

I am cozyGalvinism, second HoD of the programming team of TGP. I ask you humbly to delete this repository, as you have not obtained permission from the programming team to redistribute our decompiled code. Decompilation has always been allowed, however redistribution of the code or binaries never has been and still isn't.

If you wish to make modding easier, please consider writing an API wrapper like others did before you.

**Comment by cozyGalvinism** [comment]
Proof: 
![image](https://user-images.githubusercontent.com/1332113/235614674-a52302ee-1af5-4ede-925d-2f292fb52945.png)
![image](https://user-images.githubusercontent.com/1332113/235614751-6122f5bf-79bf-46cb-9c71-04cd3be2def0.png)

**Comment by Mae-TM** [comment]
Dear cozyGalvinism,

![image](https://user-images.githubusercontent.com/130933884/236641647-9f038549-f5dc-4bce-92e8-d91489874f3e.png)

Yours truly,
[Princess Toadstool](https://www.youtube.com/watch?v=TqKaVDo9cjs) (Peach)

**Comment by MightyButtonMasher** [comment]
For the record we have no problem with the guide itself, that's awesome. You're free to also put the guide on Steam or Discord. We'd just rather not have the source code publicly available like this. TGP as it is on Steam does not come with a license.
